version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true 
      - spring.datasource.username=root
      - spring.datasource.password=root
         
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3336:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
networks:
  springapimysql-net:
logging: 
  level:
    org.springframework.security: trace
    
